In [2]:
# import lib
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import matplotlib.pyplot as plt

In [3]:
dataset_true = pd.read_csv('True.csv')
dataset_fake = pd.read_csv('Fake.csv')
print(dataset_true)
print(dataset_fake)

                                                   title  \
0      As U.S. budget fight looms, Republicans flip t...   
1      U.S. military to accept transgender recruits o...   
2      Senior U.S. Republican senator: 'Let Mr. Muell...   
3      FBI Russia probe helped by Australian diplomat...   
4      Trump wants Postal Service to charge 'much mor...   
...                                                  ...   
21412  'Fully committed' NATO backs new U.S. approach...   
21413  LexisNexis withdrew two products from Chinese ...   
21414  Minsk cultural hub becomes haven from authorities   
21415  Vatican upbeat on possibility of Pope Francis ...   
21416  Indonesia to buy $1.14 billion worth of Russia...   

                                                    text       subject  \
0      WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1      WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2      WASHINGTON (Reuters) - The special counsel inv... 

In [4]:
df_true = dataset_true
df_fake = dataset_fake

In [45]:
df_true['Class'] = 'REAL'
df_fake['Class'] = 'FAKE'

In [46]:
df_fake.head(5)


title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date Class  
0  December 31, 2017  FAKE  
1  December 31, 2017  FAKE  
2  December 30, 2017  FAKE  
3  December 29, 2017  FAKE  
4  December 25, 2017  FAKE

In [47]:
df_true.head(5)

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date Class  
0  December 31, 2017   REAL  
1  December 29, 2017   REAL  
2  December 31, 2017   REAL  
3  December 30, 2017   REAL  
4  December 29, 2017   REAL

In [48]:
df = pd.concat([df_fake,df_true], axis = 0)
df.to_csv("News.csv")

In [49]:
df

title  \
0       Donald Trump Sends Out Embarrassing New Year’...   
1       Drunk Bragging Trump Staffer Started Russian ...   
2       Sheriff David Clarke Becomes An Internet Joke...   
3       Trump Is So Obsessed He Even Has Obama’s Name...   
4       Pope Francis Just Called Out Donald Trump Dur...   
...                                                  ...   
21412  'Fully committed' NATO backs new U.S. approach...   
21413  LexisNexis withdrew two products from Chinese ...   
21414  Minsk cultural hub becomes haven from authorities   
21415  Vatican upbeat on possibility of Pope Francis ...   
21416  Indonesia to buy $1.14 billion worth of Russia...   

                                                    text    subject  \
0      Donald Trump just couldn t wish all Americans ...       News   
1      House Intelligence Committee Chairman Devin Nu...       News   
2      On Friday, it was revealed that former Milwauk...       News   
3      On Christmas day, Donald Trump announced that ...       News   
4      Pope Francis used his annual Christmas Day mes...       News   
...                                                  ...        ...   
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...  worldnews   
21413  LONDON (Reuters) - LexisNexis, a provider of l...  worldnews   
21414  MINSK (Reuters) - In the shadow of disused Sov...  worldnews   
21415  MOSCOW (Reuters) - Vatican Secretary of State ...  worldnews   
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...  worldnews   

                    date Class  
0      December 31, 2017  FAKE  
1      December 31, 2017  FAKE  
2      December 30, 2017  FAKE  
3      December 29, 2017  FAKE  
4      December 25, 2017  FAKE  
...                  ...   ...  
21412   August 22, 2017   REAL  
21413   August 22, 2017   REAL  
21414   August 22, 2017   REAL  
21415   August 22, 2017   REAL  
21416   August 22, 2017   REAL  

[44898 rows x 5 columns]

In [50]:
df = df.drop(['subject','date'],axis=1)


In [51]:
df.columns

Index(['title', 'text', 'Class'], dtype='object')

In [52]:
# preprocess
df.isna().sum()

title    0
text     0
Class    0
dtype: int64

In [53]:
# Shuffle the DataFram
df = df.sample(frac=1).reset_index(drop=True)
df

title  \
0       NSA Chief On Trump’s Russia/US Cybersecurity ...   
1       Model Outs Men To Their Moms & Wives After Th...   
2       Here’s What The Fracking Industry Gave To Okl...   
3      SENATORS UP IN ARMS OVER OBAMA ADMINISTRATION ...   
4       Bought And Paid For: Paul Ryan Met With Insur...   
...                                                  ...   
44893  30 people killed in attack on cattle herders i...   
44894  BREAKING: US SUPREME COURT RULES King Obama Ov...   
44895  MOOCH’S TRIP TO CHINA RAN TAXPAYERS MORE THAN ...   
44896  RADICAL LEFTIST WHO DISMISSED CHARGES AGAINST ...   
44897  U.S. partnership with Turkey in Islamic State ...   

                                                    text Class  
0      It doesn t take a rocket scientist to know tha...  FAKE  
1      If you re a guy who thinks sending unwelcome d...  FAKE  
2      The fracking industry has given the state of O...  FAKE  
3      Obama is hell bent on closing GITMO before he ...  FAKE  
4      I m not sure why, after nearly a decade of Rep...  FAKE  
...                                                  ...   ...  
44893  BAUCHI, Nigeria (Reuters) - Unidentified attac...  REAL  
44894  Don t let the door hit ya B..b..but who will b...  FAKE  
44895  The whole premise of promoting education is su...  FAKE  
44896  We re not sure which of Judge Mary Murguia s q...  FAKE  
44897  WASHINGTON (Reuters) - The U.S. partnership wi...  REAL  

[44898 rows x 3 columns]

In [54]:
# input and output split
x = df['text']
y = df['Class']

In [55]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30,random_state=0)

In [56]:
# to remove stop words and to vectorize the wordings using tfid vector
tfid_vect = TfidfVectorizer(stop_words ='english',max_features=10000)
tfid_train = tfid_vect.fit_transform(x_train)
# print(tfid_train)
tfid_test = tfid_vect.transform(x_test)


In [57]:
# to get the length of vector
len(tfid_vect.get_feature_names_out())

10000

In [58]:
print(tfid_train.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [59]:
tfid_test.shape

(13470, 10000)

In [60]:
results =[]

# model creation
# Multinomial NB

Multinomial_classifier = MultinomialNB()
Multinomial_classifier.fit(tfid_train,y_train)
pred1 = Multinomial_classifier.predict(tfid_test)
score = metrics.accuracy_score(y_test,pred1)
results.append(('Multinomial NB', score))
print("Multinomial NB accuracy: %0.3f" %score)

# PassiveAggressiveClassifier
passive_classifier = PassiveAggressiveClassifier()
passive_classifier.fit(tfid_train,y_train)
pred2 = passive_classifier.predict(tfid_test)
score = metrics.accuracy_score(y_test,pred2)
results.append(('Passive Aggressive Classifier', score))
print("Passive Aggressive classifier: %0.30f" %score)

from sklearn.ensemble import RandomForestClassifier
random_classifier = RandomForestClassifier()
random_classifier.fit(tfid_train,y_train)
pred3 = random_classifier.predict(tfid_test)
score = metrics.accuracy_score(y_test,pred3)
results.append(('RandomForestClassifier',score))
print("RandomForestClassifier accuracy: %0.3f" %score)

from sklearn.tree import DecisionTreeClassifier
decisiontree_classifier = DecisionTreeClassifier()
decisiontree_classifier.fit(tfid_train,y_train)
pred4 = decisiontree_classifier.predict(tfid_test)
score = metrics.accuracy_score(y_test,pred4)
results.append(('DecisionTreeClassifier',score))
print("DecisionTreeClassifier accuracy: %0.3f" %score)

from sklearn.linear_model import LogisticRegression
logistic_classifier = LogisticRegression()
logistic_classifier.fit(tfid_train,y_train)
pred5 = logistic_classifier.predict(tfid_test)
score = metrics.accuracy_score(y_test,pred5)
results.append(('LogisticRegression',score))
print("LogisticRegression accuracy: %0.3f" %score)

# from sklearn.svm import SVC
# svc_classifier = SVC()
# svc_classifier.fit(tfid_train,y_train)
# pred = svc_classifier.predict(tfid_test)
# score = metrics.accuracy_score(y_test,pred)
# results.append(('SVC',score))
# print("SVC accuracy: %0.3f" %score)

# Create DataFrame
algorithm_comp = pd.DataFrame(results, columns=['Algorithm', 'Accuracy'])

print(algorithm_comp)


Multinomial NB accuracy: 0.935
Passive Aggressive classifier: 0.992650334075723783655575971352
RandomForestClassifier accuracy: 0.996
DecisionTreeClassifier accuracy: 0.993
LogisticRegression accuracy: 0.985
                       Algorithm  Accuracy
0                 Multinomial NB  0.934595
1  Passive Aggressive Classifier  0.992650
2         RandomForestClassifier  0.996288
3         DecisionTreeClassifier  0.992502
4             LogisticRegression  0.984633


In [61]:
# Find the algorithm with the highest accuracy
best_algorithm = max(results, key=lambda x: x[1])
best_algorithm_name = best_algorithm[0]

# Re-train the best classifier and generate the classification report
if best_algorithm_name == 'PassiveAggressive':
    best_classifier = PassiveAggressiveClassifier()
elif best_algorithm_name == 'RandomForestClassifier':
    best_classifier = RandomForestClassifier()
elif best_algorithm_name == 'DecisionTreeClassifier':
    best_classifier = DecisionTreeClassifier()
elif best_algorithm_name == 'LogisticRegression':
    best_classifier = LogisticRegression()
# elif best_algorithm_name == 'SVC':
#     best_classifier = SVC()

best_classifier.fit(tfid_train, y_train)
pred = best_classifier.predict(tfid_test)
report = metrics.classification_report(y_test, pred)
print(f"Classification Report for {best_algorithm_name}:\n{report}")

Classification Report for RandomForestClassifier:
              precision    recall  f1-score   support

        FAKE       1.00      1.00      1.00      7097
        REAL       1.00      1.00      1.00      6373

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470



In [62]:
df.iloc[10]

title    Tillerson to visit Africa in first quarter of ...
text     RAMSTEIN AIR BASE, Germany (Reuters) - U.S. Se...
Class                                                 REAL
Name: 10, dtype: object

In [23]:
best_classifier.predict(tfid_train[10])

array([1], dtype=int64)

In [63]:
text_data=['Hi,Hello...How are you?']

text_transformed = tfid_vect.transform(text_data)
text_transformed
# # Make predictions using the model
result = best_classifier.predict(text_transformed)

# Output the result
print(result)

['FAKE']


In [64]:
import pickle
filename = 'Fakenewsdectector.sav'

In [65]:
pickle.dump(best_classifier,open(filename,'wb'))

In [66]:
load_model = pickle.load(open('Fakenewsdectector.sav','rb'))

In [71]:
inputs = df.iloc[9]['text']
inputs

'BRUSSELS (Reuters) - Russian Foreign Minister Sergei Lavrov said on Wednesday it was preposterous that U.S. President Donald Trump’s eldest son was blamed for meeting a Russian lawyer who emails suggest might have had damaging information about Hillary Clinton last year. Hitting back against accusations of Russian meddling in the 206 U.S. elections, Lavrov asked to be shown “at least one fact” proving Moscow tried to interfere with the democratic process.  “I learned with surprise that a Russian lawyer, a woman, is being blamed and Trump’s son is being blamed for meeting. For me, this is wild,” Lavrov told a joint news conference with his Belgian counterpart in Brussels.     “Because when any person speaks to a lawyer, what problem or threat could there be? I didn’t know about this, I learned about it from television.” The emails released by Donald Trump Jr. on Tuesday are seen by Trump critics as the most concrete evidence yet that Trump campaign officials welcomed Russian help to wi

In [73]:
inputs = df.iloc[9][['text']]
text_transformed = tfid_vect.transform(inputs)
result = load_model.predict(text_transformed)
result

array(['REAL'], dtype=object)